//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Thu_Vien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAO
    {
        public string MaBC { get; set; }
        public string TenBC { get; set; }
        public System.DateTime NgayBC { get; set; }
        public string MaNV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
