//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Thu_Vien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public string MaPN { get; set; }
        public string MaSach { get; set; }
        public int DonGia { get; set; }
        public int SoLuong { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual PHIEUNHAPSACH PHIEUNHAPSACH { get; set; }
    }
}
