//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BAOCAO
    {
        public int Id { get; set; }
        [DisplayName("Tên")]
        public string Ten { get; set; }
        [DisplayName("Nội dung")]
        public string Description { get; set; }
        [DisplayName("Mã nhân viên")]
        public string MaNhanVien { get; set; }
        [DisplayName("Ngày lập báo cáo")]
        public Nullable<System.DateTime> NgayLapBaoCao { get; set; }
        [DisplayName("Ngày lập báo cáo")]
        public string NgayLapBaoCaoFormatted
        {
            get { return NgayLapBaoCao.HasValue ? NgayLapBaoCao.Value.ToString("dd/MM/yyyy") : string.Empty; }
        }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
