//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOITHUONG
    {
        public string MaHV { get; set; }
        public string MaSach { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual HOIVIEN HOIVIEN { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
