//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CHITIETPHIEUMUON
    {
        [DisplayName("Mã phiếu")]
        public string MaPhieu { get; set; }
        [DisplayName("Mã sách")]
        public string MaSach { get; set; }
        [DisplayName("Ngày lập phiếu")]
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        [DisplayName("Ngày lập phiếu")]
        public string NgayLapPhieuFormatted
        {
            get { return NgayLapPhieu.HasValue ? NgayLapPhieu.Value.ToString("dd/MM/yyyy") : string.Empty; }
        }
        public virtual PHIEUMUONSACH PHIEUMUONSACH { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
