//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DAUSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAUSACH()
        {
            this.SACHes = new HashSet<SACH>();
        }
        [DisplayName("Mã đầu sách")]
        public string MaDS { get; set; }
        [DisplayName("Tên sách")]
        public string TenSach { get; set; }
        [DisplayName("Thể loại")]
        public string Theloai { get; set; }
        [DisplayName("Nhà xuất bản")]
        public string NXB { get; set; }
        [DisplayName("Ngày xuất bản")]
        public System.DateTime NgayXuatBan { get; set; }
        [DisplayName("Ngày xuất bản")]
        public string NgayXuatBanFormatted
        {
            get { return NgayXuatBan.ToString("dd/MM/yyyy"); }
        }
        [DisplayName("Ghi chú")]
        public string GhiChu { get; set; }

        public virtual NhaXuatBan NhaXuatBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SACH> SACHes { get; set; }
    }
}
