//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HOIVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOIVIEN()
        {
            this.BOITHUONGs = new HashSet<BOITHUONG>();
            this.PHIEUMUONSACHes = new HashSet<PHIEUMUONSACH>();
        }
        [DisplayName("Mã hội viên")]               
        public string MaHV { get; set; }
        [DisplayName("Tên hội viên")]               
        public string TenHV { get; set; }
        [DisplayName("Số điện thoại")]               
        public string SDT { get; set; }
        [DisplayName("Ngày lập thẻ")]               
        public System.DateTime NgayLapThe { get; set; }
        [DisplayName("Ngày hết hạn")]               
        public System.DateTime NgayHetHan { get; set; }

        [DisplayName("Ngày lập thẻ")]               
        public string NgayLapTheFormatted
        {
            get { return NgayLapThe.ToString("dd/MM/yyyy"); }
        }
        [DisplayName("Ngày hết hạn")]               
        public string NgayHetHanFormatted
        {
            get { return NgayHetHan.ToString("dd/MM/yyyy"); }
        }

        [DisplayName("Tình trạng")]
        public string TinhTrang { get; set; }
        [DisplayName("Đang mượn")]
        public int DangMuon { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<int> TrangThai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOITHUONG> BOITHUONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUONSACH> PHIEUMUONSACHes { get; set; }
    }
}
