//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienCNPMNC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Quan_Ly_Thu_VienEntities : DbContext
    {
        public Quan_Ly_Thu_VienEntities()
            : base("name=Quan_Ly_Thu_VienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOCAO> BAOCAOs { get; set; }
        public virtual DbSet<BOITHUONG> BOITHUONGs { get; set; }
        public virtual DbSet<CHITIETPHIEUMUON> CHITIETPHIEUMUONs { get; set; }
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<DAUSACH> DAUSACHes { get; set; }
        public virtual DbSet<HOIVIEN> HOIVIENs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NhaXuatBan> NhaXuatBans { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<PHIEUMUONSACH> PHIEUMUONSACHes { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THAMSOQUYDINH> THAMSOQUYDINHs { get; set; }
        public virtual DbSet<MyTodo_List> MyTodo_List { get; set; }
    
        public virtual int CapNhatTinhTrangSach(string maphieu, string masach)
        {
            var maphieuParameter = maphieu != null ?
                new ObjectParameter("maphieu", maphieu) :
                new ObjectParameter("maphieu", typeof(string));
    
            var masachParameter = masach != null ?
                new ObjectParameter("masach", masach) :
                new ObjectParameter("masach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatTinhTrangSach", maphieuParameter, masachParameter);
        }
    
        public virtual int sp_BaoCao(string mABC, string tENBC, Nullable<System.DateTime> ngay, string mANV)
        {
            var mABCParameter = mABC != null ?
                new ObjectParameter("MABC", mABC) :
                new ObjectParameter("MABC", typeof(string));
    
            var tENBCParameter = tENBC != null ?
                new ObjectParameter("TENBC", tENBC) :
                new ObjectParameter("TENBC", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));
    
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BaoCao", mABCParameter, tENBCParameter, ngayParameter, mANVParameter);
        }
    
        public virtual int sp_CapNhatSoLuongSachHoiVienMuon(string mahv)
        {
            var mahvParameter = mahv != null ?
                new ObjectParameter("mahv", mahv) :
                new ObjectParameter("mahv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatSoLuongSachHoiVienMuon", mahvParameter);
        }
    
        public virtual int sp_CapNhatTinhTrangSach(string maphieu, string masach)
        {
            var maphieuParameter = maphieu != null ?
                new ObjectParameter("maphieu", maphieu) :
                new ObjectParameter("maphieu", typeof(string));
    
            var masachParameter = masach != null ?
                new ObjectParameter("masach", masach) :
                new ObjectParameter("masach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTinhTrangSach", maphieuParameter, masachParameter);
        }
    
        public virtual int sp_CapNhatTinhTrangTheHoiVien(string mahoivien)
        {
            var mahoivienParameter = mahoivien != null ?
                new ObjectParameter("mahoivien", mahoivien) :
                new ObjectParameter("mahoivien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTinhTrangTheHoiVien", mahoivienParameter);
        }
    
        public virtual ObjectResult<sp_LayThongTinNhanVien_Result> sp_LayThongTinNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayThongTinNhanVien_Result>("sp_LayThongTinNhanVien");
        }
    
        public virtual int sp_ThemNhanVien(string mANV, string tenNV, string cHUCVU, string email, string matkhau)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var cHUCVUParameter = cHUCVU != null ?
                new ObjectParameter("CHUCVU", cHUCVU) :
                new ObjectParameter("CHUCVU", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("Matkhau", matkhau) :
                new ObjectParameter("Matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", mANVParameter, tenNVParameter, cHUCVUParameter, emailParameter, matkhauParameter);
        }
    }
}
