//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTodo_List
    {
        public System.DateTime NgayTao { get; set; }
        public string MaNV { get; set; }
        public string MoTa { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
