//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PHIEUMUONSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUMUONSACH()
        {
            this.CHITIETPHIEUMUONs = new HashSet<CHITIETPHIEUMUON>();
        }
        [DisplayName("Mã phiếu")]
        public string MaPhieu { get; set; }
        [DisplayName("Mã hội viên")]
        public string MaHV { get; set; }
        [DisplayName("Ngày mượn")]
        public System.DateTime NgayMuon { get; set; }
        [DisplayName("Ngày mượn")]
        public string NgayMuonFormatted
        {
            get { return NgayMuon.ToString("dd/MM/yyyy"); }
        }
        [DisplayName("Ngày trả")]
        public Nullable<System.DateTime> NgayTra { get; set; }
        [DisplayName("Ngày trả")]
        public string NgayTraFormatted
        {
            get { return NgayTra.HasValue ? NgayTra.Value.ToString("dd/MM/yyyy") : string.Empty; }
        }
        [DisplayName("Thời hạn")]
        public System.DateTime ThoiHan { get; set; }
        [DisplayName("Thời hạn")]
        public string ThoiHanFormatted
        {
            get { return ThoiHan.ToString("dd/MM/yyyy"); }
        }
        public int SoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUMUON> CHITIETPHIEUMUONs { get; set; }
        public virtual HOIVIEN HOIVIEN { get; set; }
    }
}
